Repository semaphore-protocol/semaphore, pull requests merged in 2023-01, with the labels that each got.

#220 Semaphore `create` command
  packages/cli/README.md
  packages/cli/src/index.ts
Labels: refactoring :recycle:

#223 Fix/add ts suppress error comment
  packages/cli-template-hardhat/test/Greeter.ts
Labels: bug 🐛

#226 No version range for `snarkjs` and `poseidon-lite` dependencies
  packages/identity/package.json
  packages/proof/package.json
  yarn.lock
Labels: bug 🐛, dependencies :package:

#232 Proof generation/verification refactoring
  packages/cli-template-hardhat/package.json
  packages/cli-template-hardhat/test/Greeter.ts
  packages/cli/package.json
  packages/contracts/contracts/package.json
  packages/contracts/test/Semaphore.ts
  packages/contracts/test/SemaphoreVoting.ts
  packages/contracts/test/SemaphoreWhistleblowing.ts
  packages/group/package.json
  packages/hardhat/package.json
  packages/identity/package.json
  packages/proof/README.md
  packages/proof/package.json
  packages/proof/src/generateProof.ts
  packages/proof/src/index.test.ts
  packages/proof/src/index.ts
  packages/proof/src/packProof.ts
  packages/proof/src/packToSolidityProof.ts
  packages/proof/src/types/index.ts
  packages/proof/src/unpackProof.ts
  packages/proof/src/verifyProof.ts
  packages/subgraph/package.json
  yarn.lock
Labels: refactoring :recycle:

#236 Change a comment
  packages/group/src/group.ts
Labels: documentation 📖
