Repository semaphore-protocol/semaphore, pull requests merged in 2023-02, with the labels that each got.

#241 Group class `id` attribute
  packages/group/src/group.test.ts
  packages/group/src/group.ts
  packages/group/src/types/index.ts
Labels: feature :rocket:

#244 Check for latest version
  packages/cli/package.json
  packages/cli/src/checkLatestVersion.ts
  packages/cli/src/index.ts
  packages/cli/src/spinner.ts
  yarn.lock
Labels: feature :rocket:

#247 Integrate Inquirer.js in create command in the CLI
  packages/cli/package.json
  packages/cli/src/index.ts
  yarn.lock
Labels: feature :rocket:

#248 Add node conventions and display an error for excess arguments in commands
  packages/cli/src/index.ts
Labels: refactoring :recycle:

#251 Subgraph library improvements
  packages/subgraph/src/subgraph.test.ts
  packages/subgraph/src/subgraph.ts
  packages/subgraph/src/types/index.ts
  packages/subgraph/src/utils.ts
Labels: feature :rocket:

#250 Add inquirer in get-groups and get-group commands
  packages/cli/src/index.ts
Labels: refactoring :recycle:

#253 Yarn patch to change `changelogithub` output
  .github/workflows/release.yml
  .yarn/patches/changelogithub-npm-0.12.7-72f348805d.patch
  package.json
  yarn.lock
Labels: devops :wrench:

#255 New NPM scripts to bump versions and publish NPM packages
  .yarn/plugins/@yarnpkg/plugin-version.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: devops :wrench:

#258 Add checks for template integrity
  packages/cli/package.json
  packages/cli/src/index.ts
  packages/hardhat/README.md
  yarn.lock
Labels: feature :rocket:
