Repository semaphore-protocol/semaphore, pull requests merged in 2023-08, with the labels that each got.

#336 Add StealthComms to the projects file
  projects.json
Labels: documentation 📖

#338 New filter option to query groups based on identity commitment
  packages/data/src/subgraph.ts
  packages/data/src/types/index.ts
Labels: feature :rocket:

#347 `MerkleProof` type to exports
  packages/proof/src/index.ts
Labels: refactoring :recycle:
