Repository semaphore-protocol/semaphore, pull requests merged in 2023-04, with the labels that each got.

#299 Create hardhat-nextjs-semaphoresubgraph template in the CLI
  .prettierignore
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/.editorconfig
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/.env.example
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/.eslintignore
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/.eslintrc.json
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/.gitignore
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/.prettierignore
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/.prettierrc.json
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/.yarn/releases/yarn-3.2.1.cjs
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/.yarnrc.yml
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/README.md
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/contracts/contracts/Feedback.sol
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/contracts/hardhat.config.ts
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/contracts/package.json
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/contracts/scripts/download-snark-artifacts.ts
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/contracts/tasks/deploy.ts
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/contracts/test/Feedback.ts
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/contracts/tsconfig.json
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/contract-artifacts/Feedback.json
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/next.config.js
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/package.json
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/public/apple-touch-icon.png
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/public/favicon-16x16.png
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/public/favicon-32x32.png
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/public/favicon.ico
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/public/icon-192x192.png
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/public/icon-256x256.png
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/public/icon-384x384.png
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/public/icon-512x512.png
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/public/manifest.json
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/src/components/Stepper.tsx
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/src/context/LogsContext.ts
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/src/context/SemaphoreContext.ts
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/src/hooks/useSemaphore.ts
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/src/pages/_app.tsx
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/src/pages/api/feedback.ts
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/src/pages/api/join.ts
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/src/pages/groups.tsx
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/src/pages/index.tsx
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/src/pages/proofs.tsx
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/src/styles/globals.css
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/apps/web-app/tsconfig.json
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/package.json
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/scripts/copy-contract-artifacts.ts
  packages/cli-template-hardhat-nextjs-semaphoresubgraph/tsconfig.json
  packages/contracts/contracts/Semaphore.sol
  packages/contracts/contracts/extensions/SemaphoreVoting.sol
  packages/contracts/contracts/extensions/SemaphoreWhistleblowing.sol
  packages/contracts/contracts/interfaces/ISemaphore.sol
  packages/contracts/contracts/interfaces/ISemaphoreVoting.sol
  packages/contracts/contracts/interfaces/ISemaphoreWhistleblowing.sol
  yarn.lock
Labels: feature :rocket:

#301 Add inquirer in the CLI to select a template when creating a project
  packages/cli/src/index.ts
  packages/cli/src/inquirerPrompts.ts
Labels: feature :rocket:

#304 Correct `ProofVerified` event parameters
  packages/contracts/contracts/interfaces/ISemaphore.sol
  packages/contracts/deployed-contracts/arbitrum-goerli.json
  packages/contracts/deployed-contracts/arbitrum.json
  packages/contracts/deployed-contracts/goerli.json
  packages/contracts/deployed-contracts/mumbai.json
  packages/contracts/deployed-contracts/optimism-goerli.json
  packages/contracts/deployed-contracts/sepolia.json
  packages/data/src/ethers.ts
  packages/data/src/getURL.ts
Labels: bug 🐛

#306 chore: bump poseidon-lite minor version
  packages/group/package.json
  packages/identity/package.json
  yarn.lock
Labels: dependencies :package:

#310 Update the Readme file to add the new CLI commands
  packages/cli/README.md
Labels: documentation 📖

#313 chore: add Block Qualified to list of projects
  README.md
  projects.json
Labels: documentation 📖

#312 New function to calculate nullifier hash
  .github/workflows/docs.yml
  README.md
  packages/data/README.md
  packages/group/README.md
  packages/heyauthn/README.md
  packages/identity/README.md
  packages/proof/README.md
  packages/proof/package.json
  packages/proof/rollup.config.ts
  packages/proof/src/calculateNullifierHash.ts
  packages/proof/src/index.test.ts
  packages/proof/src/index.ts
  yarn.lock
Labels: feature :rocket:

#315 Sepolia subgraph & supported networks
  packages/cli/src/index.ts
  packages/data/README.md
  packages/data/src/ethers.ts
  packages/data/src/getSupportedNetworks.ts
  packages/data/src/getURL.ts
  packages/data/src/index.ts
  packages/data/src/subgraph.test.ts
  packages/data/src/subgraph.ts
  packages/data/src/types/index.ts
Labels: feature :rocket:
