Repository semaphore-protocol/semaphore, pull requests merged in 2023-03, with the labels that each got.

#257 add hardhat task to deploy SemaphoreVerifier.sol
  packages/hardhat/src/index.ts
  packages/hardhat/src/tasks/deploy-verifier.ts
Labels: feature :rocket:

#261 feat(identity): prepend hex strings with 0x
  packages/identity/src/identity.test.ts
  packages/identity/src/identity.ts
Labels: bug 🐛

#262 feat(identity): use sha512 to extract more entropy from message
  packages/identity/package.json
  packages/identity/src/hash.ts
  packages/identity/src/identity.test.ts
  packages/identity/src/identity.ts
  yarn.lock
Labels: bug 🐛

#267 Changing error Semaphore__InvalidProof to InvalidProof
  packages/contracts/contracts/base/Pairing.sol
  packages/contracts/test/Semaphore.ts
  packages/contracts/test/SemaphoreVoting.ts
  packages/contracts/test/SemaphoreWhistleblowing.ts
Labels: refactoring :recycle:

#268 Semaphore on Sepolia network
  packages/contracts/contracts/README.md
  packages/contracts/deployed-contracts/sepolia.json
  packages/contracts/hardhat.config.ts
Labels: devops :wrench:

#271 Poseidon lite upgrade
  packages/group/package.json
  packages/group/src/group.ts
  packages/identity/package.json
  packages/identity/src/utils.ts
  yarn.lock
Labels: refactoring :recycle:

#269 Semaphore support for Mumbai network
  packages/cli/src/index.ts
  packages/contracts/contracts/README.md
  packages/contracts/deployed-contracts/mumbai.json
  packages/contracts/hardhat.config.ts
  packages/data/src/ethers.ts
  packages/data/src/getURL.ts
  packages/data/src/types/index.ts
Labels: feature :rocket:, devops :wrench:

#270 Semaphore support for Optimism Goerli network
  packages/cli/src/index.ts
  packages/contracts/contracts/README.md
  packages/contracts/deployed-contracts/optimism-goerli.json
  packages/contracts/hardhat.config.ts
  packages/contracts/package.json
  packages/data/src/getURL.ts
  yarn.lock
Labels: feature :rocket:, devops :wrench:

#272 Correct check for group existence
  packages/data/src/ethers.test.ts
  packages/data/src/ethers.ts
Labels: bug 🐛

#273 New Github workflow to assign PRs
  .github/workflows/auto-assign.yml
Labels: devops :wrench:

#274 New Husky script to check commit messages' format
  .husky/commit-msg
  package.json
  yarn.lock
Labels: devops :wrench:

#276 JS bundles with Poseidon functions
  packages/group/package.json
  packages/group/rollup.config.ts
  packages/identity/package.json
  packages/identity/rollup.config.ts
  yarn.lock
Labels: devops :wrench:

#279 New default network (Sepolia)
  packages/data/src/ethers.test.ts
  packages/data/src/ethers.ts
Labels: refactoring :recycle:

#282 Semaphore support for Arbitrum Goerli network
  packages/contracts/deployed-contracts/arbitrum-goerli.json
  packages/contracts/hardhat.config.ts
  packages/data/src/ethers.test.ts
  packages/data/src/ethers.ts
  packages/data/src/getURL.ts
Labels: feature :rocket:, devops :wrench:

#281 Add support for Sepolia network in the CLI
  packages/cli/src/index.ts
Labels: feature :rocket:

#285 New HeyAuthn package
  packages/heyauthn/LICENSE
  packages/heyauthn/README.md
  packages/heyauthn/build.tsconfig.json
  packages/heyauthn/package.json
  packages/heyauthn/rollup.config.ts
  packages/heyauthn/src/heyAuthn.test.ts
  packages/heyauthn/src/heyAuthn.ts
  packages/heyauthn/src/index.ts
  packages/heyauthn/tsconfig.json
  yarn.lock
Labels: feature :rocket:

#291 Add new author
  packages/heyauthn/README.md
Labels: documentation 📖

#290 Split the get-group command in the CLI
  packages/cli/src/index.ts
  packages/cli/src/inquirerPrompts.ts
Labels: feature :rocket:

#293 Correct nullifier hash parameter
  packages/data/src/ethers.ts
Labels: bug 🐛

#296 Set the correct env file path
  packages/cli-template-hardhat/hardhat.config.ts
Labels: bug 🐛

#295 New identity secret attribute and getter
  packages/identity/src/identity.test.ts
  packages/identity/src/identity.ts
  packages/identity/src/utils.ts
Labels: feature :rocket:
