Repository semaphore-protocol/semaphore, pull requests merged in 2024-04, with the labels that each got.

#737 fix: incorrect alias check brought from snarkjs. (possible security vulnerability)
  packages/contracts/contracts/base/SemaphoreVerifier.sol
Labels: bug 🐛

#751 ci: fix circom deps installation steps
  .github/workflows/production.yml
  .github/workflows/pull-requests.yml
Labels: bug 🐛, devops :wrench:

#748 chore: update `.gitignore`
  .gitignore
Labels: devops :wrench:

#747 refactor!: use `maybeGetSemaphoreSnarkArtifacts` from `@zk-kit/utils
  packages/proof/README.md
  packages/proof/package.json
  packages/proof/rollup.browser.config.ts
  packages/proof/src/generate-proof.ts
  packages/proof/src/get-snark-artifacts.browser.ts
  packages/proof/src/get-snark-artifacts.node.ts
  packages/proof/src/types/index.ts
  yarn.lock
Labels: dependencies :package:, refactoring :recycle:

#754 chore(docs): format `mdx` files
  .github/pull_request_template.md
  .github/workflows/pull-requests.yml
  README.md
  apps/docs/i18n/es/docusaurus-plugin-content-docs/version-V3/guides/fetching-data.mdx
  apps/docs/i18n/es/docusaurus-plugin-content-docs/version-V3/guides/groups.mdx
  apps/docs/i18n/es/docusaurus-plugin-content-docs/version-V3/guides/identities.mdx
  apps/docs/i18n/es/docusaurus-plugin-content-docs/version-V3/guides/proofs.mdx
  apps/docs/i18n/es/docusaurus-plugin-content-docs/version-V3/quick-setup.mdx
  apps/docs/i18n/es/docusaurus-plugin-content-docs/version-V3/troubleshooting.mdx
  apps/docs/package.json
  apps/docs/versioned_docs/version-V3/guides/fetching-data.mdx
  apps/docs/versioned_docs/version-V3/guides/groups.mdx
  apps/docs/versioned_docs/version-V3/guides/identities.mdx
  apps/docs/versioned_docs/version-V3/guides/proofs.mdx
  apps/docs/versioned_docs/version-V3/quick-setup.mdx
  apps/docs/versioned_docs/version-V3/troubleshooting.mdx
  apps/docs/versioned_docs/version-V4-beta/getting-started.mdx
  apps/docs/versioned_docs/version-V4-beta/guides/groups.mdx
  apps/docs/versioned_docs/version-V4-beta/guides/identities.mdx
  apps/docs/versioned_docs/version-V4-beta/guides/proofs.mdx
  apps/docs/versioned_docs/version-V4-beta/subgraph.mdx
  package.json
  yarn.lock
Labels: documentation 📖, devops :wrench:
